site_name: openocean-messages
repo_url: https://github.com/openocean-software/openocean-messages
docs_dir: src/doc

theme:
  name: material

nav:
  - Home: index.md
  - Messages: messages.md
  - Building: building.md
  - Using from another project: using.md
  - Outputs:
      - C++: cxx.md
      - Python: python.md
      - nanopb: nanopb.md
      - Rust: rust.md
      - ROS 2: ros.md
      - LCM: lcm.md
  - Compatibility checks: compatibility.md
  - Development: development.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
