// Generated by protoc-gen-lcm: converts between the openocean.test Protobuf
// and LCM C++ types.
#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include "google/protobuf/duration.pb.h"
#include "google/protobuf/timestamp.pb.h"
#include "mapping.pb.h"

#include "openocean/test/mapping_inner_t.hpp"
#include "openocean/test/mapping_t.hpp"

#include "openocean/lcm_convert.h"

namespace openocean::test
{
namespace lcm_detail
{
inline int64_t to_int64(uint64_t value, const char* field)
{
    if (value > static_cast<uint64_t>(std::numeric_limits<int64_t>::max()))
        throw std::out_of_range(std::string(field) + " does not fit in an LCM int64_t");
    return static_cast<int64_t>(value);
}

inline uint64_t to_uint64(int64_t value, const char* field)
{
    if (value < 0)
        throw std::out_of_range(std::string(field) + " is negative");
    return static_cast<uint64_t>(value);
}

inline uint32_t to_uint32(int64_t value, const char* field)
{
    if (value < 0 || value > std::numeric_limits<uint32_t>::max())
        throw std::out_of_range(std::string(field) + " does not fit in a uint32");
    return static_cast<uint32_t>(value);
}

inline int32_t to_count(std::size_t size, const char* field)
{
    if (size > static_cast<std::size_t>(std::numeric_limits<int32_t>::max()))
        throw std::out_of_range(std::string(field) + " has too many elements for LCM");
    return static_cast<int32_t>(size);
}

inline void check_count(int32_t count, std::size_t size, const char* field)
{
    if (count < 0 || static_cast<std::size_t>(count) != size)
        throw std::invalid_argument(std::string(field) + " count does not match its size");
}

// Truncates to whole microseconds
template <typename T> int64_t to_micros(const T& t)
{
    return t.seconds() * 1000000 + t.nanos() / 1000;
}

// Timestamp nanos are always non-negative
template <typename T> void from_micros_timestamp(int64_t micros, T* t)
{
    int64_t seconds = micros / 1000000, remainder = micros % 1000000;
    if (remainder < 0)
    {
        remainder += 1000000;
        --seconds;
    }
    t->set_seconds(seconds);
    t->set_nanos(static_cast<int32_t>(remainder * 1000));
}

// Duration nanos have the sign of the seconds
template <typename T> void from_micros_duration(int64_t micros, T* t)
{
    t->set_seconds(micros / 1000000);
    t->set_nanos(static_cast<int32_t>(micros % 1000000 * 1000));
}

// Map iteration order is unspecified, so sort for a deterministic LCM encoding
template <typename Map> std::vector<const typename Map::value_type*> sorted(const Map& map)
{
    std::vector<const typename Map::value_type*> entries;
    for (const auto& kv : map) entries.push_back(&kv);
    std::sort(entries.begin(), entries.end(),
              [](const auto* a, const auto* b) { return a->first < b->first; });
    return entries;
}
} // namespace lcm_detail

inline void to_lcm(const ::openocean::test::Mapping& in, ::openocean::test::mapping_t* out);
inline void from_lcm(const ::openocean::test::mapping_t& in, ::openocean::test::Mapping* out);
inline void to_lcm(const ::openocean::test::Mapping_Inner& in, ::openocean::test::mapping_inner_t* out);
inline void from_lcm(const ::openocean::test::mapping_inner_t& in, ::openocean::test::Mapping_Inner* out);

inline void to_lcm(const ::openocean::test::Mapping& in, ::openocean::test::mapping_t* out)
{
    *out = ::openocean::test::mapping_t();
    out->implicit_presence = in.implicit_presence();
    out->has_explicit_presence = in.has_explicit_presence();
    out->explicit_presence = in.explicit_presence();
    for (const auto& e : in.counts())
    {
        out->counts.emplace_back();
        out->counts.back() = e;
    }
    out->num_counts = lcm_detail::to_count(out->counts.size(), "openocean.test.Mapping.counts");
    out->data.assign(in.data().begin(), in.data().end());
    out->num_data = lcm_detail::to_count(out->data.size(), "openocean.test.Mapping.data");
    out->color.value = static_cast<int32_t>(in.color());
    out->has_sign = in.has_sign();
    out->sign.value = static_cast<int32_t>(in.sign());
    out->stamp_ms = in.stamp_ms();
    out->has_stamp = in.has_stamp();
    out->stamp = lcm_detail::to_micros(in.stamp());
    out->has_period = in.has_period();
    out->period = lcm_detail::to_micros(in.period());
    out->has_inner = in.has_inner();
    to_lcm(in.inner(), &out->inner);
    for (const auto& e : in.inners())
    {
        out->inners.emplace_back();
        to_lcm(e, &out->inners.back());
    }
    out->num_inners = lcm_detail::to_count(out->inners.size(), "openocean.test.Mapping.inners");
    out->choice_case = static_cast<int32_t>(in.choice_case());
    out->a = in.a();
    to_lcm(in.b(), &out->b);
    for (const auto* kv : lcm_detail::sorted(in.table()))
    {
        out->table.emplace_back();
        out->table.back().key = kv->first;
        out->table.back().value = kv->second;
    }
    out->num_table = lcm_detail::to_count(out->table.size(), "openocean.test.Mapping.table");
    for (const auto* kv : lcm_detail::sorted(in.by_id()))
    {
        out->by_id.emplace_back();
        out->by_id.back().key = kv->first;
        to_lcm(kv->second, &out->by_id.back().value);
    }
    out->num_by_id = lcm_detail::to_count(out->by_id.size(), "openocean.test.Mapping.by_id");
    out->big = lcm_detail::to_int64(in.big(), "openocean.test.Mapping.big");
    out->small = in.small();
    out->has_speed = in.has_speed();
    to_lcm(in.speed(), &out->speed);
    out->mode.value = static_cast<int32_t>(in.mode());
}

inline void from_lcm(const ::openocean::test::mapping_t& in, ::openocean::test::Mapping* out)
{
    out->Clear();
    out->set_implicit_presence(in.implicit_presence);
    if (in.has_explicit_presence)
        out->set_explicit_presence(in.explicit_presence);
    lcm_detail::check_count(in.num_counts, in.counts.size(), "openocean.test.Mapping.counts");
    for (const auto& e : in.counts)
        out->add_counts(e);
    lcm_detail::check_count(in.num_data, in.data.size(), "openocean.test.Mapping.data");
    out->set_data(std::string(in.data.begin(), in.data.end()));
    out->set_color(static_cast<::openocean::test::Mapping_Color>(in.color.value));
    if (in.has_sign)
        out->set_sign(static_cast<::openocean::test::Mapping_Signed>(in.sign.value));
    out->set_stamp_ms(in.stamp_ms);
    if (in.has_stamp)
        lcm_detail::from_micros_timestamp(in.stamp, out->mutable_stamp());
    if (in.has_period)
        lcm_detail::from_micros_duration(in.period, out->mutable_period());
    if (in.has_inner)
        from_lcm(in.inner, out->mutable_inner());
    lcm_detail::check_count(in.num_inners, in.inners.size(), "openocean.test.Mapping.inners");
    for (const auto& e : in.inners)
        from_lcm(e, out->add_inners());
    switch (in.choice_case)
    {
        case 12:
            out->set_a(in.a);
            break;
        case 13:
            from_lcm(in.b, out->mutable_b());
            break;
        default:
            break;
    }
    lcm_detail::check_count(in.num_table, in.table.size(), "openocean.test.Mapping.table");
    for (const auto& e : in.table)
        (*out->mutable_table())[e.key] = e.value;
    lcm_detail::check_count(in.num_by_id, in.by_id.size(), "openocean.test.Mapping.by_id");
    for (const auto& e : in.by_id)
        from_lcm(e.value, &(*out->mutable_by_id())[e.key]);
    out->set_big(lcm_detail::to_uint64(in.big, "openocean.test.Mapping.big"));
    out->set_small(lcm_detail::to_uint32(in.small, "openocean.test.Mapping.small"));
    if (in.has_speed)
        from_lcm(in.speed, out->mutable_speed());
    out->set_mode(static_cast<::openocean::SpeedMode>(in.mode.value));
}

inline void to_lcm(const ::openocean::test::Mapping_Inner& in, ::openocean::test::mapping_inner_t* out)
{
    *out = ::openocean::test::mapping_inner_t();
    out->name = in.name();
}

inline void from_lcm(const ::openocean::test::mapping_inner_t& in, ::openocean::test::Mapping_Inner* out)
{
    out->Clear();
    out->set_name(in.name);
}

} // namespace openocean::test
