#!/usr/bin/env python3
"""protoc plugin that generates a ROS 2 interface package.

protoc --plugin=protoc-gen-ros=protoc-gen-ros \
    --ros_out=package=NAME,maintainer=NAME,maintainer_email=EMAIL,license=LICENSE[,version=X.Y.Z][,description=TEXT]:OUT_DIR \
    -I IMPORT_DIR file.proto...
"""

import sys

from google.protobuf.compiler import plugin_pb2

from openocean_gen import model, ros


def main():
    request = plugin_pb2.CodeGeneratorRequest.FromString(sys.stdin.buffer.read())
    response = plugin_pb2.CodeGeneratorResponse(
        supported_features=plugin_pb2.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL)
    try:
        files = ros.generate(model.build(request), model.parse_parameters(request.parameter))
        for name, content in files.items():
            response.file.add(name=name, content=content)
    except model.GeneratorError as e:
        response.error = str(e)
    sys.stdout.buffer.write(response.SerializeToString())


if __name__ == "__main__":
    main()
