#!/usr/bin/env python3
"""protoc plugin that generates LCM types, and a C++ header converting between them and
the Protobuf C++ types.

protoc --plugin=protoc-gen-lcm=protoc-gen-lcm --lcm_out=header=PATH/lcm_convert.h:OUT_DIR \
    -I IMPORT_DIR file.proto...
"""

from openocean_gen import lcm, model

if __name__ == "__main__":
    model.run_plugin(lcm.generate)
