// Generated by protoc-gen-ros: converts between the openocean.test Protobuf
// and openocean_test_msgs ROS 2 C++ types.
#pragma once

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>

#include "google/protobuf/duration.pb.h"
#include "google/protobuf/timestamp.pb.h"
#include "mapping.pb.h"

#include "builtin_interfaces/msg/duration.hpp"
#include "builtin_interfaces/msg/time.hpp"
#include "openocean_test_msgs/msg/mapping.hpp"
#include "openocean_test_msgs/msg/mapping_inner.hpp"

namespace openocean::test
{
namespace ros_detail
{
inline int32_t to_ros_seconds(int64_t seconds, const char* field)
{
    if (seconds < std::numeric_limits<int32_t>::min() || seconds > std::numeric_limits<int32_t>::max())
        throw std::out_of_range(std::string(field) + " is outside builtin_interfaces' int32 seconds");
    return static_cast<int32_t>(seconds);
}

// value in units since 1970 (units_per_second of them per second)
template <typename Int>
builtin_interfaces::msg::Time to_time(Int value, int64_t units_per_second, const char* field)
{
    if constexpr (std::is_unsigned_v<Int>)
    {
        if (value > static_cast<uint64_t>(std::numeric_limits<int64_t>::max()))
            throw std::out_of_range(std::string(field) + " does not fit in int64");
    }
    int64_t v = static_cast<int64_t>(value);
    int64_t seconds = v / units_per_second, remainder = v % units_per_second;
    if (remainder < 0)
    {
        remainder += units_per_second;
        --seconds;
    }
    builtin_interfaces::msg::Time t;
    t.sec = to_ros_seconds(seconds, field);
    t.nanosec = static_cast<uint32_t>(remainder * (1000000000 / units_per_second));
    return t;
}

// Truncates to whole units
template <typename Int>
Int from_time(const builtin_interfaces::msg::Time& t, int64_t units_per_second, const char* field)
{
    int64_t v = t.sec * units_per_second + t.nanosec / (1000000000 / units_per_second);
    bool fits;
    if constexpr (std::is_unsigned_v<Int>)
        fits = v >= 0 && static_cast<uint64_t>(v) <= std::numeric_limits<Int>::max();
    else
        fits = v >= std::numeric_limits<Int>::min() && v <= std::numeric_limits<Int>::max();
    if (!fits)
        throw std::out_of_range(std::string(field) + " does not fit its Protobuf type");
    return static_cast<Int>(v);
}

inline builtin_interfaces::msg::Time to_time_seconds(double seconds, const char* field)
{
    double whole = std::floor(seconds);
    builtin_interfaces::msg::Time t;
    t.sec = to_ros_seconds(static_cast<int64_t>(whole), field);
    t.nanosec = static_cast<uint32_t>(std::min((seconds - whole) * 1e9, 999999999.0));
    return t;
}

inline double from_time_seconds(const builtin_interfaces::msg::Time& t)
{
    return t.sec + t.nanosec * 1e-9;
}

template <typename Timestamp>
builtin_interfaces::msg::Time to_time(const Timestamp& timestamp, const char* field)
{
    builtin_interfaces::msg::Time t;
    t.sec = to_ros_seconds(timestamp.seconds(), field);
    t.nanosec = static_cast<uint32_t>(timestamp.nanos());
    return t;
}

template <typename Timestamp> void from_time(const builtin_interfaces::msg::Time& t, Timestamp* timestamp)
{
    timestamp->set_seconds(t.sec);
    timestamp->set_nanos(static_cast<int32_t>(t.nanosec));
}

// Protobuf Duration nanos have the sign of the seconds; builtin_interfaces nanosec is never negative
template <typename Duration>
builtin_interfaces::msg::Duration to_duration(const Duration& duration, const char* field)
{
    int64_t nanos = static_cast<int64_t>(to_ros_seconds(duration.seconds(), field)) * 1000000000 +
                    duration.nanos();
    int64_t seconds = nanos / 1000000000, remainder = nanos % 1000000000;
    if (remainder < 0)
    {
        remainder += 1000000000;
        --seconds;
    }
    builtin_interfaces::msg::Duration d;
    d.sec = to_ros_seconds(seconds, field);
    d.nanosec = static_cast<uint32_t>(remainder);
    return d;
}

template <typename Duration> void from_duration(const builtin_interfaces::msg::Duration& d, Duration* duration)
{
    int64_t nanos = static_cast<int64_t>(d.sec) * 1000000000 + d.nanosec;
    duration->set_seconds(nanos / 1000000000);
    duration->set_nanos(static_cast<int32_t>(nanos % 1000000000));
}

// Map iteration order is unspecified, so sort for a deterministic ROS message
template <typename Map> std::vector<const typename Map::value_type*> sorted(const Map& map)
{
    std::vector<const typename Map::value_type*> entries;
    for (const auto& kv : map) entries.push_back(&kv);
    std::sort(entries.begin(), entries.end(),
              [](const auto* a, const auto* b) { return a->first < b->first; });
    return entries;
}
} // namespace ros_detail

inline void to_ros(const ::openocean::test::Mapping& in, ::openocean_test_msgs::msg::Mapping* out);
inline void from_ros(const ::openocean_test_msgs::msg::Mapping& in, ::openocean::test::Mapping* out);
inline void to_ros(const ::openocean::test::Mapping_Inner& in, ::openocean_test_msgs::msg::MappingInner* out);
inline void from_ros(const ::openocean_test_msgs::msg::MappingInner& in, ::openocean::test::Mapping_Inner* out);

inline void to_ros(const ::openocean::test::Mapping& in, ::openocean_test_msgs::msg::Mapping* out)
{
    *out = ::openocean_test_msgs::msg::Mapping();
    out->implicit_presence = in.implicit_presence();
    out->has_explicit_presence = in.has_explicit_presence();
    out->explicit_presence = in.explicit_presence();
    for (const auto& e : in.counts())
    {
        out->counts.emplace_back();
        out->counts.back() = e;
    }
    out->data.assign(in.data().begin(), in.data().end());
    out->color.value = static_cast<uint8_t>(in.color());
    out->has_sign = in.has_sign();
    out->sign.value = static_cast<int32_t>(in.sign());
    out->stamp_ms = ros_detail::to_time(in.stamp_ms(), 1000, "openocean.test.Mapping.stamp_ms");
    out->has_stamp = in.has_stamp();
    out->stamp = ros_detail::to_time(in.stamp(), "openocean.test.Mapping.stamp");
    out->has_period = in.has_period();
    out->period = ros_detail::to_duration(in.period(), "openocean.test.Mapping.period");
    out->has_inner = in.has_inner();
    to_ros(in.inner(), &out->inner);
    for (const auto& e : in.inners())
    {
        out->inners.emplace_back();
        to_ros(e, &out->inners.back());
    }
    out->choice_case = static_cast<uint8_t>(in.choice_case());
    out->a = in.a();
    to_ros(in.b(), &out->b);
    for (const auto* kv : ros_detail::sorted(in.table()))
    {
        out->table.emplace_back();
        out->table.back().key = kv->first;
        out->table.back().value = kv->second;
    }
    for (const auto* kv : ros_detail::sorted(in.by_id()))
    {
        out->by_id.emplace_back();
        out->by_id.back().key = kv->first;
        to_ros(kv->second, &out->by_id.back().value);
    }
    out->big = in.big();
    out->small = in.small();
}

inline void from_ros(const ::openocean_test_msgs::msg::Mapping& in, ::openocean::test::Mapping* out)
{
    out->Clear();
    out->set_implicit_presence(in.implicit_presence);
    if (in.has_explicit_presence)
        out->set_explicit_presence(in.explicit_presence);
    for (const auto& e : in.counts)
        out->add_counts(e);
    out->set_data(std::string(in.data.begin(), in.data.end()));
    out->set_color(static_cast<::openocean::test::Mapping_Color>(in.color.value));
    if (in.has_sign)
        out->set_sign(static_cast<::openocean::test::Mapping_Signed>(in.sign.value));
    out->set_stamp_ms(ros_detail::from_time<int64_t>(in.stamp_ms, 1000, "openocean.test.Mapping.stamp_ms"));
    if (in.has_stamp)
        ros_detail::from_time(in.stamp, out->mutable_stamp());
    if (in.has_period)
        ros_detail::from_duration(in.period, out->mutable_period());
    if (in.has_inner)
        from_ros(in.inner, out->mutable_inner());
    for (const auto& e : in.inners)
        from_ros(e, out->add_inners());
    switch (in.choice_case)
    {
        case 12:
            out->set_a(in.a);
            break;
        case 13:
            from_ros(in.b, out->mutable_b());
            break;
        default:
            break;
    }
    for (const auto& e : in.table)
        (*out->mutable_table())[e.key] = e.value;
    for (const auto& e : in.by_id)
        from_ros(e.value, &(*out->mutable_by_id())[e.key]);
    out->set_big(in.big);
    out->set_small(in.small);
}

inline void to_ros(const ::openocean::test::Mapping_Inner& in, ::openocean_test_msgs::msg::MappingInner* out)
{
    *out = ::openocean_test_msgs::msg::MappingInner();
    out->name = in.name();
}

inline void from_ros(const ::openocean_test_msgs::msg::MappingInner& in, ::openocean::test::Mapping_Inner* out)
{
    out->Clear();
    out->set_name(in.name);
}

} // namespace openocean::test
