<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>openocean_msgs_check</name>
  <version>0.0.0</version>
  <description>Uses the generated ROS 2 messages from C++</description>
  <maintainer email="toby@oceansoft.org">Toby Schneider</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>openocean_msgs</depend>
  <depend>openocean_test_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
