syntax = "proto3";

package openocean;

import "openocean/messages/common.proto";
import "openocean/messages/options.proto";

// Frames:
//  - geodetic: WGS-84 latitude, longitude, and depth (positive down)
//  - enu: ENU e (east), n (north), u (up) relative to the datum,
//    so u = -depth
//  - body: x forward, y starboard, z down (Fossen / SNAME)
message Navigation
{
    uint64 time = 1 [(openocean.field).units =
                         "microseconds since 1970-01-01 00:00:00 UTC"];

    message VehicleMetadata
    {
        string name = 1;
    }

    VehicleMetadata vehicle = 2;

    message Geodetic
    {
        optional double latitude = 1
            [(openocean.field).units = "degrees_north"];
        optional double longitude = 2
            [(openocean.field).units = "degrees_east"];
        optional double depth = 3 [(openocean.field).units = "m"];
    }
    optional Geodetic geodetic = 10;

    message ENU
    {
        optional double datum_latitude = 1
            [(openocean.field).units = "degrees_north"];
        optional double datum_longitude = 2
            [(openocean.field).units = "degrees_east"];
        optional double e = 3 [(openocean.field).units = "m"];
        optional double n = 4 [(openocean.field).units = "m"];
        optional double u = 5 [(openocean.field).units = "m"];
    }
    optional ENU enu = 11;

    // defined in common.proto
    optional Euler attitude = 12;

    message Velocity
    {
        optional double u = 1 [(openocean.field).units = "m/s"];
        optional double v = 2 [(openocean.field).units = "m/s"];
        optional double w = 3 [(openocean.field).units = "m/s"];
        // defined in common.proto
        optional SpeedMode mode = 4;
    }

    // repeated so that speed over water and/or speed over ground can be reported
    repeated Speed speed = 13;
    // ditto for dx/dt, etc. velocities
    repeated Velocity velocity = 14;

    optional double altitude = 15 [(openocean.field).units = "m"];
    optional double course_over_ground = 16 [(openocean.field).units = "rad"];

    message AngularVelocity
    {
        optional double p = 1 [(openocean.field).units = "rad/s"];
        optional double q = 2 [(openocean.field).units = "rad/s"];
        optional double r = 3 [(openocean.field).units = "rad/s"];
    }
    optional AngularVelocity angular_velocity = 17;

    message Acceleration
    {
        optional double du_dt = 1 [(openocean.field).units = "m/s^2"];
        optional double dv_dt = 2 [(openocean.field).units = "m/s^2"];
        optional double dw_dt = 3 [(openocean.field).units = "m/s^2"];
    }
    optional Acceleration acceleration = 18;

    message AngularAcceleration
    {
        optional double dp_dt = 1 [(openocean.field).units = "rad/s^2"];
        optional double dq_dt = 2 [(openocean.field).units = "rad/s^2"];
        optional double dr_dt = 3 [(openocean.field).units = "rad/s^2"];
    }
    optional AngularAcceleration angular_acceleration = 19;
}
